export enum OutboxEventTypeEnum {
  GENERATE_TASK_EMBEDDINGS = 'GENERATE_TASK_EMBEDDINGS',
  GENERATE_COLUMN_EMBEDDINGS = 'GENERATE_COLUMN_EMBEDDINGS',
  GENERATE_BOARD_EMBEDDINGS = 'GENERATE_BOARD_EMBEDDINGS',
  GENERATE_WORKSPACE_EMBEDDINGS = 'GENERATE_WORKSPACE_EMBEDDINGS',
}
