export enum ErrorsMessage {
  SERVER_ERROR = 'Возникла непредвиденная ошибка.',
  INVALID_CREDENTIALS = 'Неверный email или пароль.',
  USER_NOT_FOUND = 'Пользователь не найден.',
  EMAIL_ALREADY_EXISTS = 'Пользователь с таким email уже существует.',
  PASSWORD_TOO_SHORT = 'Пароль должен содержать не менее 6 символов.',
  INVALID_EMAIL_FORMAT = 'Неверный формат электронной почты.',
  TOKEN_GENERATION_FAILED = 'Не удалось сгенерировать токен.',
  TOKEN_NOT_FOUND = 'Токен не найден.',
  WORKSPACE_NAME_REQUIRED = 'Требуется название рабочего пространства.',
  WORKSPACE_NAME_INVALID = 'Неверное название рабочего пространства.',
  WORKSPACE_COLOR_REQUIRED = 'Требуется цвет рабочего пространства.',
  INVALID_ID_FORMAT = 'Неверный формат идентификатора.',
  WORKSPACE_ID_INVALID = 'Неверный идентификатор рабочего пространства.',
  WORKSPACE_ID_REQUIRED = 'Требуется идентификатор рабочего пространства.',
  EMAIL_REQUIRED = 'Требуется электронная почта.',
  PASSWORD_REQUIRED = 'Требуется пароль.',
  INVALID_PASSWORD_FORMAT = 'Неверный формат пароля.',
}
