export enum ErrorsMessage {
  SERVER_ERROR = 'Возникла непредвиденная ошибка.',
  INVALID_CREDENTIALS = 'Неверный email или пароль.',
  INVALID_CURRENT_PASSWORD = 'Неверный текущий пароль.',
  USER_NOT_FOUND = 'Пользователь не найден.',
  EMAIL_ALREADY_EXISTS = 'Пользователь с таким email уже существует.',
  PASSWORD_TOO_SHORT = 'Пароль должен содержать не менее 6 символов.',
  PASSWORD_TOO_LONG = 'Пароль не должен превышать 100 символов.',
  PASSWORD_SAME_AS_OLD = 'Новый пароль не должен совпадать с текущим.',
  INVALID_EMAIL_FORMAT = 'Неверный формат электронной почты.',
  TOKEN_GENERATION_FAILED = 'Не удалось сгенерировать токен.',
  TOKEN_NOT_FOUND = 'Токен не найден.',

  WORKSPACE_NAME_REQUIRED = 'Требуется название пространства.',
  WORKSPACE_NAME_INVALID = 'Неверное название пространства.',
  WORKSPACE_NAME_LESS_THAN_1 = 'Название пространства не должно быть пустым.',
  WORKSPACE_NAME_MORE_THAN_100 = 'Название пространства не должно превышать 100 символов.',
  WORKSPACE_COLOR_REQUIRED = 'Требуется цвет пространства.',
  WORKSPACE_ORDER_TYPE_INVALID = 'Неверный порядок пространства.',

  BOARD_NAME_REQUIRED = 'Требуется название доски.',
  BOARD_NAME_INVALID = 'Неверное название доски.',
  BOARD_NAME_LESS_THAN_1 = 'Название доски не должно быть пустым.',
  BOARD_NAME_MORE_THAN_100 = 'Название доски не должно превышать 100 символов.',
  BOARD_ORDER_TYPE_INVALID = 'Неверный порядок доски.',
  BOARD_IS_FAVORITE_TYPE_INVALID = 'Неверное значение у доски для добавления в избранное.',

  CATEGORY_NAME_REQUIRED = 'Требуется название категории.',
  CATEGORY_NAME_INVALID = 'Неверное название категории.',
  CATEGORY_NAME_LESS_THAN_1 = 'Название категории не должно быть пустым.',
  CATEGORY_NAME_MORE_THAN_100 = 'Название категории не должно превышать 100 символов.',
  CATEGORY_ORDER_TYPE_INVALID = 'Неверный порядок категории.',
  CATEGORY_ID_REQUIRED = 'Требуется идентификатор категории.',
  CATEGORY_ID_INVALID = 'Неверный идентификатор категории.',
  CATEGORIES_BULK_UPDATE_INVALID = 'Неверные данные для массового обновления категорий.',

  TASK_ID_INVALID = 'Неверный идентификатор задачи.',
  TASK_NAME_REQUIRED = 'Требуется название задачи.',
  TASK_NAME_INVALID = 'Неверное название задачи.',
  TASK_NAME_LESS_THAN_1 = 'Название задачи не должно быть пустым.',
  TASK_NAME_MORE_THAN_100 = 'Название задачи не должно превышать 100 символов.',
  TASK_DESCRIPTION_INVALID = 'Неверное описание задачи.',
  TASK_DESCRIPTION_LESS_THAN_1 = 'Описание задачи не должно быть пустым.',
  TASK_DESCRIPTION_MORE_THAN_300 = 'Описание задачи не должно превышать 300 символов.',
  TASK_DUE_DATE_INVALID = 'Неверная дата выполнения задачи.',
  TASK_DUE_TIME_INVALID = 'Неверное время выполнения задачи.',
  TASK_COLOR_REQUIRED = 'Требуется цвет задачи.',
  TASK_TAGS_INVALID_TYPE = 'Неверный тип тегов задачи.',
  TASK_ORDER_TYPE_INVALID = 'Неверный порядок задачи.',
  TASK_IS_COMPLETED_INVALID = 'Неверное значение для статуса задачи.',
  TASKS_BULK_UPDATE_INVALID = 'Неверные данные для массового обновления задач.',

  USER_ID_INVALID = 'Неверный идентификатор пользователя.',
  USERNAME_TOO_SHORT = 'Имя пользователя должно содержать не менее 1 символа.',
  USERNAME_TOO_LONG = 'Имя пользователя не должно превышать 50 символов.',
  USER_COLOR_REQUIRED = 'Требуется цвет пользователя.',
  TIMEZONE_REQUIRED = 'Требуется часовой пояс.',
  INVALID_TIMEZONE = 'Неверный часовой пояс.',

  SETTING_AI_NAME_TOO_SHORT = 'Название ИИ должно содержать не менее 1 символа.',
  SETTING_AI_NAME_TOO_LONG = 'Название ИИ не должно превышать 50 символов.',
  SETTING_AI_CONFIRMATION_TYPE_REQUIRED = 'Требуется тип подтверждения ИИ.',
  SETTING_AI_DEFAULT_CATEGORY_TOO_LONG = 'Категория по умолчанию для ИИ не должна превышать 100 символов.',
  SETTING_AI_DEFAULT_BOARD_TOO_LONG = 'Доска по умолчанию для ИИ не должна превышать 100 символов.',
  SETTING_ID_INVALID = 'Неверный идентификатор настройки.',

  PAYMENT_DESCRIPTION_TOO_SHORT = 'Описание платежа должно содержать не менее 1 символа.',
  PAYMENT_DESCRIPTION_TOO_LONG = 'Описание платежа не должно превышать 255 символов.',
  PAYMENT_AMOUNT_TOO_SMALL = 'Сумма платежа должна быть не менее 0.01.',
  PAYMENT_CURRENCY_INVALID = 'Валюта платежа должна содержать ровно 3 символа.',
  PAYMENT_STATUS_INVALID = 'Неверный статус платежа.',

  PAYMENT_METHOD_SERVICE_ID_REQUIRED = 'Требуется идентификатор сервиса метода оплаты.',
  PAYMENT_METHOD_TYPE_REQUIRED = 'Требуется тип метода оплаты.',
  PAYMENT_METHOD_CARD_FIRST6_INVALID = 'Первые 6 цифр карты метода оплаты неверны.',
  PAYMENT_METHOD_CARD_LAST4_INVALID = 'Последние 4 цифры карты метода оплаты неверны.',
  PAYMENT_METHOD_CARD_TYPE_REQUIRED = 'Требуется тип карты метода оплаты.',
  PAYMENT_METHOD_LAST4_INVALID = 'Последние 4 цифры метода оплаты неверны.',
  PAYMENT_METHOD_EXPIRY_MONTH_INVALID = 'Неверный месяц истечения срока действия метода оплаты.',
  PAYMENT_METHOD_EXPIRY_YEAR_INVALID = 'Неверный год истечения срока действия метода оплаты.',
  PAYMENT_METHOD_ID_REQUIRED = 'Требуется идентификатор метода оплаты.',
  INVALID_PAYMENT_METHOD_ID = 'Неверный идентификатор метода оплаты.',

  OPERATION_LOG_NOT_FOUND = 'Запись журнала операций не найдена.',

  SUBSCRIPTION_PLAN_NOT_FOUND = 'План подписки не найден. Обратитесь в поддержку.',
  INVALID_ID_FORMAT = 'Неверный формат идентификатора.',
  WORKSPACE_ID_INVALID = 'Неверный идентификатор рабочего пространства.',
  WORKSPACE_ID_REQUIRED = 'Требуется идентификатор рабочего пространства.',
  BOARD_ID_INVALID = 'Неверный идентификатор доски.',
  BOARD_ID_REQUIRED = 'Требуется идентификатор доски.',
  EMAIL_REQUIRED = 'Требуется электронная почта.',
  PASSWORD_REQUIRED = 'Требуется пароль.',
  INVALID_PASSWORD_FORMAT = 'Неверный формат пароля.',
  THREAD_ID_INVALID = 'Неверный идентификатор чата.',
}
