export enum ErrorsMessage {
  SERVER_ERROR = 'Возникла непредвиденная ошибка.',
  INVALID_CREDENTIALS = 'Неверный email или пароль.',
  USER_NOT_FOUND = 'Пользователь не найден.',
  EMAIL_ALREADY_EXISTS = 'Пользователь с таким email уже существует.',
  PASSWORD_TOO_SHORT = 'Пароль должен содержать не менее 6 символов.',
  INVALID_EMAIL_FORMAT = 'Неверный формат электронной почты.',
  TOKEN_GENERATION_FAILED = 'Не удалось сгенерировать токен.',
  TOKEN_NOT_FOUND = 'Токен не найден.',

  WORKSPACE_NAME_REQUIRED = 'Требуется название пространства.',
  WORKSPACE_NAME_INVALID = 'Неверное название пространства.',
  WORKSPACE_NAME_LESS_THAN_1 = 'Название пространства не должно быть пустым.',
  WORKSPACE_NAME_MORE_THAN_100 = 'Название пространства не должно превышать 100 символов.',
  WORKSPACE_COLOR_REQUIRED = 'Требуется цвет пространства.',
  WORKSPACE_ORDER_TYPE_INVALID = 'Неверный порядок пространства.',

  BOARD_NAME_REQUIRED = 'Требуется название доски.',
  BOARD_NAME_INVALID = 'Неверное название доски.',
  BOARD_NAME_LESS_THAN_1 = 'Название доски не должно быть пустым.',
  BOARD_NAME_MORE_THAN_100 = 'Название доски не должно превышать 100 символов.',
  BOARD_ORDER_TYPE_INVALID = 'Неверный порядок доски.',

  CATEGORY_NAME_REQUIRED = 'Требуется название категории.',
  CATEGORY_NAME_INVALID = 'Неверное название категории.',
  CATEGORY_NAME_LESS_THAN_1 = 'Название категории не должно быть пустым.',
  CATEGORY_NAME_MORE_THAN_100 = 'Название категории не должно превышать 100 символов.',
  CATEGORY_ORDER_TYPE_INVALID = 'Неверный порядок категории.',
  CATEGORY_ID_REQUIRED = 'Требуется идентификатор категории.',
  CATEGORY_ID_INVALID = 'Неверный идентификатор категории.',

  TASK_ID_INVALID = 'Неверный идентификатор задачи.',
  TASK_NAME_REQUIRED = 'Требуется название задачи.',
  TASK_NAME_INVALID = 'Неверное название задачи.',
  TASK_NAME_LESS_THAN_1 = 'Название задачи не должно быть пустым.',
  TASK_NAME_MORE_THAN_100 = 'Название задачи не должно превышать 100 символов.',
  TASK_DESCRIPTION_INVALID = 'Неверное описание задачи.',
  TASK_DESCRIPTION_LESS_THAN_1 = 'Описание задачи не должно быть пустым.',
  TASK_DESCRIPTION_MORE_THAN_300 = 'Описание задачи не должно превышать 300 символов.',
  TASK_DUE_DATE_INVALID = 'Неверная дата выполнения задачи.',
  TASK_DUE_TIME_INVALID = 'Неверное время выполнения задачи.',
  TASK_COLOR_REQUIRED = 'Требуется цвет задачи.',
  TASK_TAGS_INVALID_TYPE = 'Неверный тип тегов задачи.',
  TASK_ORDER_TYPE_INVALID = 'Неверный порядок задачи.',
  TASK_IS_COMPLETED_INVALID = 'Неверное значение для статуса задачи.',
  TASKS_BULK_UPDATE_INVALID = 'Неверные данные для массового обновления задач.',

  INVALID_ID_FORMAT = 'Неверный формат идентификатора.',
  WORKSPACE_ID_INVALID = 'Неверный идентификатор рабочего пространства.',
  WORKSPACE_ID_REQUIRED = 'Требуется идентификатор рабочего пространства.',
  BOARD_ID_INVALID = 'Неверный идентификатор доски.',
  BOARD_ID_REQUIRED = 'Требуется идентификатор доски.',
  EMAIL_REQUIRED = 'Требуется электронная почта.',
  PASSWORD_REQUIRED = 'Требуется пароль.',
  INVALID_PASSWORD_FORMAT = 'Неверный формат пароля.',
}
