import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'

export const CreateCategoryDTOSchema = z
  .object({
    _id: z.string(), // It generated by python code, but we need it to be able to link created task with the one in DB after creation
    name: z
      .string({
        error: (iss) =>
          iss.input === undefined
            ? ErrorMessages.TASK_NAME_REQUIRED
            : ErrorMessages.TASK_NAME_INVALID,
      })
      .min(1, ErrorMessages.TASK_NAME_LESS_THAN_1)
      .max(100, ErrorMessages.TASK_NAME_MORE_THAN_100),
    board: z.string({
      error: (iss) =>
        iss.input === undefined ? ErrorMessages.BOARD_ID_REQUIRED : ErrorMessages.BOARD_ID_INVALID,
    }),
    workspace: z
      .string({
        error: (iss) =>
          iss.input === undefined
            ? ErrorMessages.WORKSPACE_ID_REQUIRED
            : ErrorMessages.WORKSPACE_ID_INVALID,
      })
      .optional(),
  })
  .strict()

export const CreateCategoriesDTOSchema = z.object({
  categories: CreateCategoryDTOSchema.array(),
})

export type CreateCategoriesDTO = z.infer<typeof CreateCategoriesDTOSchema>
