import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const MoveBoardDTOSchema = z
  .object({
    id: z.string(),
    before_id: z.string(ErrorMessages.BOARD_ID_INVALID).nullable().optional(),
    after_id: z.string(ErrorMessages.BOARD_ID_INVALID).nullable().optional(),
    new_workspace_id: z.string(ErrorMessages.WORKSPACE_ID_INVALID).nullable().optional(),
  })
  .strict()

export type MoveBoardDTO = z.infer<typeof MoveBoardDTOSchema>
