import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const MoveTaskDTOSchema = z
  .object({
    id: z.string(),
    before_task_id: z.string(ErrorMessages.TASK_ID_INVALID).nullable().optional(),
    after_task_id: z.string(ErrorMessages.TASK_ID_INVALID).nullable().optional(),
    new_category_id: z.string(ErrorMessages.CATEGORY_ID_INVALID).nullable().optional(),
  })
  .strict()

export type MoveTaskDTO = z.infer<typeof MoveTaskDTOSchema>
