import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'
import { CreateCategoryDTOSchema } from './CreateCategoriesDTO.ts'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const UpdateCategoryDTOSchema = CreateCategoryDTOSchema.partial()
  .extend({
    _id: z.string(ErrorMessages.CATEGORY_ID_INVALID),
  })
  .strict()

export const UpdateCategoriesDTOSchema = z.object({
  updates: UpdateCategoryDTOSchema.array(),
})

export type UpdateCategoriesDTO = z.infer<typeof UpdateCategoriesDTOSchema>
