import { ErrorMessages } from '@/enums/ErrorMessages.js'
import { z } from 'zod'
import { CreateTaskDTOSchema } from './CreateTasksDTO.js'
import { TASK_COLORS_TITLES } from '@/constants/TASK_COLORS.js'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const UpdateTaskDTOSchema = CreateTaskDTOSchema.partial()
  .extend({
    _id: z.string(ErrorMessages.TASK_ID_INVALID),
    description: z
      .string(ErrorMessages.TASK_DESCRIPTION_INVALID)
      .max(1000, ErrorMessages.TASK_DESCRIPTION_MORE_THAN_1000)
      .nullable()
      .optional(),
    due_date: z.iso.date(ErrorMessages.TASK_DUE_DATE_INVALID).nullable().optional(),
    due_hours: z.number(ErrorMessages.TASK_DUE_TIME_INVALID).min(0).max(23).nullable().optional(),
    due_minutes: z.number(ErrorMessages.TASK_DUE_TIME_INVALID).min(0).max(59).nullable().optional(),
    priority: z
      .enum(['low', 'medium', 'high'], {
        error: (iss) =>
          iss.input === undefined
            ? ErrorMessages.TASK_PRIORITY_REQUIRED
            : ErrorMessages.TASK_PRIORITY_INVALID,
      })
      .nullable()
      .optional(),
    color: z
      .object({
        value: z.enum(TASK_COLORS_TITLES, {
          error: (iss) =>
            iss.input === undefined
              ? ErrorMessages.TASK_COLOR_REQUIRED
              : 'Неверное значение для цвета.',
        }),
        tone: z.enum(['light', 'medium', 'dark'], {
          error: (iss) =>
            iss.input === undefined
              ? ErrorMessages.TASK_COLOR_REQUIRED
              : 'Неверное значение для цвета.',
        }),
      })
      .nullable()
      .optional(),
  })
  .strict()

export const UpdateTasksDTOSchema = z.object({
  updates: UpdateTaskDTOSchema.array(),
})

export type UpdateTasksDTO = z.infer<typeof UpdateTasksDTOSchema>
