import { ErrorMessages } from '@/enums/ErrorMessages.js'
import { z } from 'zod'
import { CreateWorkspaceDTOSchema } from './CreateWorkspacesDTO.js'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const UpdateWorkspaceDTOSchema = CreateWorkspaceDTOSchema.partial()
  .extend({
    _id: z.string(ErrorMessages.WORKSPACE_ID_INVALID),
  })
  .strict()

export const UpdateWorkspacesDTOSchema = z.object({
  updates: UpdateWorkspaceDTOSchema.array(),
})

export type UpdateWorkspacesDTO = z.infer<typeof UpdateWorkspacesDTOSchema>
