import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'
import { CreateBoardDTOSchema } from './CreateBoardsDTO.ts'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const UpdateBoardDTOSchema = CreateBoardDTOSchema.partial()
  .extend({
    _id: z.string(ErrorMessages.BOARD_ID_INVALID),
  })
  .strict()

export const UpdateBoardsDTOSchema = z.object({
  updates: UpdateBoardDTOSchema.array(),
})

export type UpdateBoardsDTO = z.infer<typeof UpdateBoardsDTOSchema>
