import { ErrorMessages } from '@/enums/ErrorMessages.ts'
import { z } from 'zod'
import { CreateTaskDTOSchema } from './CreateTasksDTO.ts'

/**
 * ids here are generated by python code, so we can't validate them with regex, but we need them to be able to link created task with the one in DB after creation
 */
export const UpdateTaskDTOSchema = CreateTaskDTOSchema.partial()
  .extend({
    _id: z.string(ErrorMessages.TASK_ID_INVALID),
  })
  .strict()

export const UpdateTasksDTOSchema = z.object({
  updates: UpdateTaskDTOSchema.array(),
})

export type UpdateTasksDTO = z.infer<typeof UpdateTasksDTOSchema>
