export const TOOLS_CUSTOM_DESCRIPTIONS: Record<string, string> = {
  findTasksByFilter: 'Finds tasks matching specific filter criteria.',
  searchRelevantTasks: 'Searches for relevant tasks by their names.',
  createTasks: 'Creates new tasks.',
  archiveTasks: 'Archives specified tasks.',
  cloneTasks: 'Duplicates existing tasks.',
  recoverTasks: 'Restores previously archived tasks.',
  deleteTasks: 'Permanently deletes tasks.',
  updateTasksName: 'Modifies the names of specified tasks.',
  updateTasksDescription: 'Modifies the descriptions of specified tasks.',
  updateTasksDueDate: 'Updates the due dates of specified tasks.',
  updateTasksDueTime: 'Updates the due times of specified tasks.',
  updateTasksTags: 'Modifies the tags associated with specified tasks.',
  updateTasksColor: 'Changes the color of specified tasks.',
  updateTasksOrder: 'Updates the sorting order of specified tasks.',
  moveTasks: 'Moves specified tasks to a different category.',
  completeTasks: 'Marks specified tasks as completed or incomplete.',
  findCategoriesByFilter: 'Finds categories matching specific filter criteria.',
  searchRelevantCategories: 'Searches for relevant categories by their names.',
  createCategories: 'Creates new categories.',
  archiveCategories: 'Archives specified categories.',
  cloneCategories: 'Duplicates existing categories.',
  recoverCategories: 'Restores previously archived categories.',
  deleteCategories: 'Permanently deletes categories.',
  updateCategoriesName: 'Modifies the names of specified categories.',
  updateCategoriesOrder: 'Updates the sorting order of specified categories.',
  moveCategories: 'Moves specified categories to a different board.',
  findBoardsByFilter: 'Finds boards matching specific filter criteria.',
  searchRelevantBoards: 'Searches for relevant boards by their names.',
  createBoards: 'Creates new boards.',
  archiveBoards: 'Archives specified boards.',
  cloneBoards: 'Duplicates existing boards.',
  recoverBoards: 'Restores previously archived boards.',
  deleteBoards: 'Permanently deletes boards.',
  updateBoardsName: 'Modifies the names of specified boards.',
  updateBoardsOrder: 'Updates the sorting order of specified boards.',
  moveBoards: 'Moves specified boards to a different workspace.',
  favoriteBoards: 'Marks or unmarks specified boards as favorites.',
  findWorkspacesByFilter: 'Finds workspaces matching specific filter criteria.',
  searchRelevantWorkspaces: 'Searches for relevant workspaces by their names.',
  createWorkspaces: 'Creates new workspaces.',
  archiveWorkspaces: 'Archives specified workspaces.',
  cloneWorkspaces: 'Duplicates existing workspaces.',
  recoverWorkspaces: 'Restores previously archived workspaces.',
  deleteWorkspaces: 'Permanently deletes workspaces.',
  updateWorkspacesName: 'Modifies the names of specified workspaces.',
  updateWorkspacesOrder: 'Updates the sorting order of specified workspaces.',
  updateWorkspacesColor: 'Changes the color of specified workspaces.',
  favoriteWorkspaces: 'Marks or unmarks specified workspaces as favorites.',
  showEntitiesToUser: 'Shows specified entities to the user in the interface.',
  undoOperations: 'Reverts a set of previously performed operations.',
  getRelevantTools: 'Internal tool for self-analysis to expand the set of available tools.',
  finishResponse: 'Delivers the final text response to the user.',
  executePlan: "Submits a logical sequence of atomic steps to fulfill the user's request.",
  responseToUser:
    'Explains issues to the user, such as missing information or errors, in a conversational manner.',
}
